insert into `bbs_brand` VALUES(11,'莱尔瑜伽',null,null,null,89,'1');
insert into `bbs_brand` VALUES(12, '轻装服装',null,null,null,90,'1');
insert into `bbs_brand` VALUES(13, '艾米达',null,null,null,88,'1');
insert into `bbs_brand` VALUES(14, '哈他',null,null,null,78,'1');
insert into `bbs_brand` VALUES(15, '詹姆斯',null,null,null,78,'1');
insert into `bbs_brand` VALUES(16, '瑜伽树',null,null,null,68,'1');
insert into `bbs_brand` VALUES(17, '蓝一博人',null,null,null,70,'1');
insert into `bbs_brand` VALUES(18, 'Eff',null,null,null,48,'1');
insert into `bbs_brand` VALUES(19, '凯苏',null,null,null,58,'1');
insert into `bbs_brand` VALUES(20, '扶苏',null,null,null,68,'1');
insert into `bbs_brand` VALUES(21, '天蓝',null,null,null,68,'1');
insert into `bbs_brand` VALUES(22, '地方',null,null,null,55,'1');